def rename_dict():
    return {
        'ALT_SGPT_1_1': 'ALT/SGPT',
        'APT_APTR_1_1': 'aPTT',
        'AST_SGOT_1_1': 'AST SGOT',
        'Adenovirus': 'Adenovirus confirmed',
        'Bacteria': 'Bacteria in Sputum',
        'Bleeding_Haemorrhage': 'Haemorrhage',
        'Blood_Urea_Nitrogen_value_1': 'Blood Urea Nitrogen',
        'Blood_albumin_value_1': 'Blood albumin',
        'CT_thorax_performed': 'Thoracic CT findings',
        'Calcium_adm': 'Calcium in blood',
        'Creatinine_value_1': 'Creatinine in blood',
        'Dyspnea': 'Dyspnea',
        'Glucose_unit_1_1': 'Glucose in blood',
        'Haemoglobin_value_1': 'Haemoglobin',
        'HtR': 'Heart rate',
        'INR_1_1': 'INR',
        'Influenza': 'Influenza confirmed',
        'LDH': 'LDH',
        'Lactate_2_1': 'Lactate',
        'Lymphocyte_1_1': 'Lymphocyte count',
        'Neutrophil_unit_1': 'Neutrophil count',
        'PCO2_1': 'PCO2',
        'PH_value_1': 'PH',
        'PaO2_1_Arterial': 'PaO2 (arterial)',
        'PaO2_1_Capillary': 'PaO2 (capillary)',
        'PaO2_1_Venous': 'PaO2 (Venous)',
        'Platelets_value_1': 'Platelets',
        'Potassium_1_1': 'Potassium',
        'Record Id': None,
        'SaO2_1': 'SaO2',
        'Seizures': 'Seizures', # Experiencing during admission or as comorbidity?
        'Sodium_1_1': 'Sodium',
        'Temperature': 'Temperature',
        'Total_Bilirubin_2_1': 'Bilirubin',
        'WBC_2_1': 'White Bloodcell count',
        'age_yrs': 'Age',
        'aids_hiv': 'AIDS / HIV',
        'asthma': 'Asthma',
        'autoimm_disorder_1': 'Autoimmune disorder',
        'capillary_refill': 'Disturbed capillary refill',
        'ccd': 'Chronic cardiac disease',
        'chd': 'Chronic hematologic disease',
        'ckd': 'Chronic kidney disease',
        'cnd': 'Chronic neurological disease',
        'corads_admission_cat_1': 'CO-RADS (No)',
        'corads_admission_cat_2': 'CO-RADS (Low)',
        'corads_admission_cat_3': 'CO-RADS (Intermediate)',
        'corads_admission_cat_4': 'CO-RADS (High)',
        'corads_admission_cat_5': 'CO-RADS (Very high)',
        'corads_admission_cat_missing': 'CO-RADS missing value',
        'cpd': 'Chronic pulmonary disease',
        'creatininekinase': 'Creatine Kinase',
        'crp_1_1': 'CRP', # Full name?
        'culture': 'Blood culture',
        'd_dimer': 'D-dimer',
        'days_untreated': 'Days between onset & admissions',
        'diabetes_complications': 'Diabetes with complications',
        'diabetes_without_complications': 'Diabetes without complications',
        'dias_bp': 'Diastolic blood pressure',
        'ferritine_admin_spec': 'Ferritine',
        'fever': 'Fever',
        'fibrinogen_admin': 'Fibrinogen (Factor I)',
        'fio2_1': 'FiO2',
        'gender_cat_1': 'Gender (Male)',
        'gender_cat_2': 'Gender (Female)',
        'gender_cat_3': 'Gender (Not Specified)',
        'gender_cat_missing': 'Gender (Missing value)',
        'healthcare_worker': 'Healthcare worker',
        'home_medication': 'Regular home medication',
        'hospital': None,
        'hypertension': 'Hypertension',
        'immune_sup': 'Immunosuppressive medication',
        'infec_resp_diagnosis': 'Infectious Respiratory diagnosis (other)',
        'infiltrates_2': 'Infiltrates',
        'irregular': 'Irregular heart rhythm',
        'live_disease': 'Liver disease (moderate to severe)',
        'microbiology_worker': 'Microbiology worker',
        'mld': 'Liver disease (Mild)',
        'mneoplasm': 'Malignant Neoplasm',
        'oxygen_saturation': 'Oxygen saturation',
        'oxygen_saturation_on_cat_1': 'Oxygen saturation on room air',
        'oxygen_saturation_on_cat_2': 'Oxygen saturation on oxygen therapy',
        'oxygen_saturation_on_cat_3': 'Oxygen saturation on (unknown)',
        'oxygen_saturation_on_cat_missing': 'Oxygen saturation on (missing)',
        'pt_spec': 'PT', # Fullname?
        'rheuma_disorder': 'Rheumatologic disorder',
        'rtr': 'Respiratory rate',
        'sys_bp': 'Systolic blood pressure',
        'uses_n_medicine': 'Number of medications'
        }
