def get_unit_lookup_dict():
    # -999.0 means the value is multiplied with the white blood value count (WBC)
    lookup_dict = {'Birth_weight_unit':          {1: 1.0,    2: 0.4536             },
                   'units_neutro':               {1: 0.001,  2: -999.0, 3: 1.0     },
                   'Platelets_unit_1':           {1: 1.0,    2: 1.0                },
                   'Total_Bilirubin_1_1':        {1: 0.0585, 2: 1.0                },
                   'Haemoglobin_unit_1':         {1: 0.1,    2: 1.0,    3: 1.6114  },
                   'Glucose_unit_2':             {1: 18.016, 2: 1.0                },
                   'Blood_Urea_Nitrogen_unit_1': {1: 2.8,    2: 1.0                },
                   'Lactate_1_1':                {1: 9.008,  2: 1.0                },
                   'Creatinine_unit_1':          {1: 0.0113, 2: 1.0                },
                   'sodium_units':               {1: 1.0,    2: 1.0                },
                   'pot_units_1':                {1: 1.0,    2: 1.0                },
                   'd_dimer_units_adm':          {1: 1000.0, 2: 1.0,    3: 0.18    },
                   'WBC_1_1':                    {1: 1.0,    2: 1.0                },
                   'units_lymph':                {1: 0.001,  2: -999.0, 3: 1.0     },
                   'PCO2_unit_1':                {1: 7.5006, 2: 1.0                },
                   'PaO2un_1':                   {1: 7.5006, 2: 1.0                },
                   'PaO2un':                     {1: 7.5006, 2: 1.0                },
                   'PCO2_unit':                  {1: 7.5006, 2: 1.0                },
                   'lymph_units_1':              {1: 0.001,  2: -999.0, 3: 1.0     },
                   'neutro_units_2':             {1: 0.001,  2: -999.0, 3: 1.0     },
                   'Platelets_unit':             {1: 1.0,    2: 1.0                },
                   'Total_Bilirubin_1':          {1: 0.0585, 2: 1.0                },
                   'Glucose_unit':               {1: 18.016, 2: 1.0                },
                   'Blood_Urea_Nitrogen_unit':   {1: 2.8,    2: 1.0                },
                   'Lactate_1':                  {1: 9.008,  2: 1.0                },
                   'Creatinine_unit':            {1: 0.0113, 2: 1.0                },
                   'sodium_units_1':             {1: 1.0,    2: 1.0                },
                   'pot_units_2':                {1: 1.0,    2: 1.0                },
                   'Haemoglobin_unit':           {1: 0.1,    2: 1.0,    3: 1.6114  },
                   'units_d_dimer':              {1: 1000.0, 2: 1.0,    3: 0.18    }, 
                   'WBC_1':                      {1: 1.0,    2: 1.0                }}


    numeric_vars = {'infant_birth_weight':'Birth_weight_unit',
                    'Neutrophil_unit_1':'units_neutro',
                    'Platelets_value_1':'Platelets_unit_1',
                    'Total_Bilirubin_2_1':'Total_Bilirubin_1_1',
                    'Haemoglobin_value_1':'Haemoglobin_unit_1',
                    'Glucose_unit_1_1':'Glucose_unit_2',
                    'Blood_Urea_Nitrogen_value_1':'Blood_Urea_Nitrogen_unit_1',
                    'Lactate_2_1':'Lactate_1_1',
                    'Creatinine_value_1':'Creatinine_unit_1',
                    'Sodium_1_1':'sodium_units',
                    'Potassium_1_1':'pot_units_1',
                    'd_dimer':'d_dimer_units_adm',
                    'WBC_2_1':'WBC_1_1',
                    'Lymphocyte_1_1':'units_lymph',
                    'PCO2_1':'PCO2_unit_1',
                    'PaO2_1':'PaO2un_1',
                    'PaO2':'PaO2un',
                    'PCO2':'PCO2_unit',
                    'Lymphocyte_1':'lymph_units_1',
                    'Neutrophil_unit':'neutro_units_2',
                    'Platelets_value':'Platelets_unit',
                    'Total_Bilirubin_2':'Total_Bilirubin_1',
                    'Glucose_unit_1':'Glucose_unit',
                    'Blood_Urea_Nitrogen_value':'Blood_Urea_Nitrogen_unit',
                    'Lactate_2':'Lactate_1',
                    'Creatinine_value':'Creatinine_unit',
                    'Sodium_1':'sodium_units_1',
                    'Potassium_1':'pot_units_2',
                    'Haemoglobin_value':'Haemoglobin_unit',
                    'ddimer_value_daily':'units_d_dimer',
                    'WBC_2':'WBC_1'}
    return lookup_dict, numeric_vars



        # numeric_vars = {'Birth_weight_unit': 'infant_birth_weight',
        #             'units_neutro': 'Neutrophil_unit_1',
        #             'Platelets_unit_1': 'Platelets_unit_1', 
        #             'Total_Bilirubin_1_1': 'Total_Bilirubin_2_1',
        #             'Haemoglobin_unit_1': 'Haemoglobin_value_1',
        #             'Glucose_unit_2': 'Glucose_unit_1_1',
        #             'Blood_Urea_Nitrogen_unit_1': 'Blood_Urea_Nitrogen_value_1',
        #             'Lactate_1_1': 'Lactate_2_1', 
        #             'Creatinine_unit_1': 'Creatinine_value_1',
        #             'sodium_units': 'Sodium_1_1', 
        #             'pot_units_1': 'Potassium_1_1',
        #             'd_dimer_units_adm': 'd_dimer',
        #             'WBC_1_1': 'WBC_2_1',
        #             'units_lymph': 'Lymphocyte_1_1',
        #             'PCO2_unit_1': 'PCO2_1',
        #             'PaO2un_1': 'PaO2_1',
        #             'PaO2un': 'PaO2',
        #             'PCO2_unit': 'PCO2',
        #             'lymph_units_1': 'Lymphocyte_1',
        #             'neutro_units_2': 'Neutrophil_unit',
        #             'Platelets_unit': 'Platelets_value',
        #             'Total_Bilirubin_1': 'Total_Bilirubin_2', 
        #             'Glucose_unit': 'Glucose_unit_1',
        #             'Blood_Urea_Nitrogen_unit': 'Blood_Urea_Nitrogen_value',
        #             'Lactate_1': 'Lactate_2',
        #             'Creatinine_unit': 'Creatinine_value',
        #             'sodium_units_1': 'Sodium_1',
        #             'pot_units_2': 'Potassium_1', 
        #             'Haemoglobin_unit': 'Haemoglobin_value',
        #             'units_d_dimer': 'ddimer_value_daily',
        #             'WBC_1': 'WBC_2'}
                    