def get_unit_lookup_dict():
    # -999.0 means the value is multiplied with the white blood value count (WBC)
    lookup_dict = {'Birth_weight_unit':          {1: 1.0,    2: 0.4536             },
                   'units_neutro':               {1: 0.001,  2: -999.0,    3: 1.0  },
                   'Platelets_unit_1':           {1: 1.0,    2: 1.0                },
                   'Total_Bilirubin_1_1':        {1: 1.0,    2: 17.1               },
                   'Haemoglobin_unit_1':         {1: 1.6114, 2: 16.1140,   3: 1    },
                   'Glucose_unit_2':             {1: 1.0,    2: 0.0555             },
                   'Blood_Urea_Nitrogen_unit_1': {1: 1.0,    2: 0.3571             },
                   'Lactate_1_1':                {1: 1.0,    2: 0.1110             },
                   'Creatinine_unit_1':          {1: 1.0,    2: 88.4956            },
                   'sodium_units':               {1: 1.0,    2: 1.0                },
                   'pot_units_1':                {1: 1.0,    2: 1.0                },
                   'd_dimer_units_adm':          {1: 1000.0, 2: 0.18,      3: 1    },
                   'WBC_1_1':                    {1: 1.0,    2: 1.0                },
                   'units_lymph':                {1: 0.001,  2: -999.0,    3: 1.0  },
                   'PCO2_unit_1':                {1: 1.0,    2: 0.1333             },
                   'PaO2un_1':                   {1: 1.0,    2: 0.1333             },
                   'PaO2un':                     {1: 1.0,    2: 0.1333             },
                   'PCO2_unit':                  {1: 1.0,    2: 0.1333             },
                   'lymph_units_1':              {1: 0.001,  2: -999.0,    3: 1.0  },
                   'neutro_units_2':             {1: 0.001,  2: -999.0,    3: 1.0  },
                   'Platelets_unit':             {1: 1.0,    2: 1.0                },
                   'Total_Bilirubin_1':          {1: 1.0,    2: 17.1               },
                   'Glucose_unit':               {1: 1.0,    2: 0.0555             },
                   'Blood_Urea_Nitrogen_unit':   {1: 1.0,    2: 0.3571             },
                   'Lactate_1':                  {1: 1.0,    2: 0.1110             },
                   'Creatinine_unit':            {1: 1.0,    2: 88.4956            },
                   'sodium_units_1':             {1: 1.0,    2: 1.0                },
                   'pot_units_2':                {1: 1.0,    2: 1.0                },
                   'Haemoglobin_unit':           {1: 1.6114, 2: 16.1140,   3: 1    },
                   'units_d_dimer':              {1: 1000.0, 2: 0.18,      3: 1    }, 
                   'WBC_1':                      {1: 1.0,    2: 1.0                }}


    numeric_vars = {'infant_birth_weight':'Birth_weight_unit',
                    'Neutrophil_unit_1':'units_neutro',
                    'Platelets_value_1':'Platelets_unit_1',
                    'Total_Bilirubin_2_1':'Total_Bilirubin_1_1',
                    'Haemoglobin_value_1':'Haemoglobin_unit_1',
                    'Glucose_unit_1_1':'Glucose_unit_2',
                    'Blood_Urea_Nitrogen_value_1':'Blood_Urea_Nitrogen_unit_1',
                    'Lactate_2_1':'Lactate_1_1',
                    'Creatinine_value_1':'Creatinine_unit_1',
                    'Sodium_1_1':'sodium_units',
                    'Potassium_1_1':'pot_units_1',
                    'd_dimer':'d_dimer_units_adm',
                    'WBC_2_1':'WBC_1_1',
                    'Lymphocyte_1_1':'units_lymph',
                    'PCO2_1':'PCO2_unit_1',
                    'PaO2_1':'PaO2un_1',
                    'PaO2':'PaO2un',
                    'PCO2':'PCO2_unit',
                    'Lymphocyte_1':'lymph_units_1',
                    'Neutrophil_unit':'neutro_units_2',
                    'Platelets_value':'Platelets_unit',
                    'Total_Bilirubin_2':'Total_Bilirubin_1',
                    'Glucose_unit_1':'Glucose_unit',
                    'Blood_Urea_Nitrogen_value':'Blood_Urea_Nitrogen_unit',
                    'Lactate_2':'Lactate_1',
                    'Creatinine_value':'Creatinine_unit',
                    'Sodium_1':'sodium_units_1',
                    'Potassium_1':'pot_units_2',
                    'Haemoglobin_value':'Haemoglobin_unit',
                    'ddimer_value_daily':'units_d_dimer',
                    'WBC_2':'WBC_1'}
    return lookup_dict, numeric_vars